spring:
  security:
    oauth2:
      client:
        registration:
          nufirst:
            client-secret: "{cipher}429817f73dc348cdadd91e150e4842760508148e79182cf4a540cee9bc3740d56e30eff9d19ac6a9369c179251869010466c259b32c29ff3591fd08289c11046"
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost,http://localhost:8181,https://nufirst.cluster.local,http://localhost:8762"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "authorization, content-type, xsrf-token, X-Requested-With, X-Authorization, X-Frame-Options, File-Name, file-firstName, Access-Control-Request-Headers, Content-Type, Time-Zone, User-TimeZone, Default-TimeZone, Device-Type, Device-ID, X-File-Name, X-File-Size, X-File-Type, X-Filename-Encoder, X-File-Scanned, X-File-Modified, X-File-AType"
            exposeHeaders: "xsrf-token, file-firstName, File-Name, Content-Type, Time-Zone"
            maxAge: 3600
            allowCredentials: true