nufirst:
  databaseName: "MAIN_BACKEND"

spring:  
  security:
    oauth2:
      client:
        registration:
          nufirst:
            client-secret: "{cipher}e4f92f5400acbdb12c161365f27b2b7b2ef397cbf453a36c671c154dad77fa5102a2a26d5d90f6a9b8cfabf4678326e01f9639f9cce0168bec141fcde51785ee"
  datasource:
    url: "jdbc:mysql://localhost:3306/MAIN_BACKEND?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&cacheDefaultTimezone=false"
  jpa:
    show-sql: true

springdoc:
  swagger-ui:
    oauth:
      client-secret: "{cipher}e4f92f5400acbdb12c161365f27b2b7b2ef397cbf453a36c671c154dad77fa5102a2a26d5d90f6a9b8cfabf4678326e01f9639f9cce0168bec141fcde51785ee"