spring:
  security:
    oauth2:
      client:
        registration:
          nufirst:
            client-secret: "{cipher}05869c4bdc3af8485ead33d73b801b78a604be2374b45fa6eca498c9ba3dc100789ea554df8c44fb386c9ec11868ccbbbfc73f491036c699f9c6164b691cd711"
  datasource:
    url: "jdbc:mysql://localhost:3306?useSSL=false&useTimezone=true&useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&cacheDefaultTimezone=false"

executor:
  mainDatabase: "MAIN_BACKEND"

springdoc:
  swagger-ui:
    oauth:
      client-secret: "{cipher}05869c4bdc3af8485ead33d73b801b78a604be2374b45fa6eca498c9ba3dc100789ea554df8c44fb386c9ec11868ccbbbfc73f491036c699f9c6164b691cd711"