nufirst:
  databaseName: "SMS_GATEWAY"

spring:
  security:
    oauth2:
      client:
        registration:
          nufirst:
            client-secret: "{cipher}7581803aa965b17a9dd7d5c79f941748b6072485184aaea8f59453cf8057212dbc285330f5a20bf87ad6f31c922106559e5acd4276b57660a470e7a677c2f8ea"
  datasource:
    url: "jdbc:mysql://mysql:3306/SMS_GATEWAY?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC"

sms:
  providerClass: "cloud.nufirst.smsgateway.skebby.SkebbyGateway"
  config:
    username: ""
    password: ""

springdoc:
  swagger-ui:
    oauth:
      client-secret: "{cipher}7581803aa965b17a9dd7d5c79f941748b6072485184aaea8f59453cf8057212dbc285330f5a20bf87ad6f31c922106559e5acd4276b57660a470e7a677c2f8ea"

eureka:
  instance:
    hostname: sms-gateway